### ISSUE TITLE
Screenshot loaded as null on some device

### ISSUE THREAD

**Issue by nkming2** [nkming2/power-menu#18]
Screenshot loaded as null on some device, not sure why...

Stacktrace:
```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.nkming.powermenu.ScreenshotHandler$_notifyScreenshot$1._getThumbnail(ScreenshotHandler.kt:188)
	at com.nkming.powermenu.ScreenshotHandler$_notifyScreenshot$1.doInBackground(ScreenshotHandler.kt:108)
	at com.nkming.powermenu.ScreenshotHandler$_notifyScreenshot$1.doInBackground(ScreenshotHandler.kt:103)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by nkming2** [comment]
screencap erred with ```Unable to get handle for display 0```

**Comment by nkming2** [comment]
Possible workaround: https://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_SYSRQ

**Comment by mirko77** [comment]
I just installed the app and it fails to take a screenshot on my Moto G5, Android 7.

Is this issue related?

**Comment by nkming2** [comment]
Possible. Sadly I'm not too sure what's causing this issue. One thing clear is that it's to some extend related to the root solution used. For example on the same N5, I could reproduce it with SuperSU before but no longer with the latest Magisk

**Comment by mirko77** [comment]
@nkming2 I rooted my phone with Magisk and I have this issue...well, I guess. It says "Failed to take a screenshot" but I have not looked at the logs yet.

**Comment by nkming2** [comment]
I've just published a beta on the Play Store which may be able to workaround this issue. Can you help trying that out to see if it works? To join beta, scroll to the bottom of the app page. Thanks :)

**Comment by nkming2** [comment]
Related: b4fba00f70d87ac81cc228d0ed0f12a486ff0b79

**Comment by mirko77** [comment]
I confirm the issue is solved on the new beta, I'm able to get the
screenshot correctly!

There is only a small delay, 1 sec or so before it gets taken, but I can
leave with that! Many thanks ;)
