### ISSUE TITLE
NPE if activity ended before su return

### ISSUE THREAD

**Issue by nkming2** [nkming2/power-menu#7]
Log:

```
java.lang.NullPointerException
    at com.nkming.powermenu.MainFragment$7.onSuResult(MainFragment.java:276)
    at com.nkming.powermenu.SystemHelper$1.onPostExecute(SystemHelper.java:118)
    at com.nkming.powermenu.SystemHelper$1.onPostExecute(SystemHelper.java:89)
    ...
```

**Comment by nkming2** [comment]
Fixed automatically with the migration to kotlin :smile:
